AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  L2 Blue Print - WebServer with Auto Scaling Group and Network Load Balancer

Parameters:

  KeyName:
    Type: String
    Description: Name of RSA key for EC2 access for testing only.
    Default: ''

  VpcId:
    Description: VPC where resources will be provisioned
    Type: "AWS::EC2::VPC::Id"

  PrivateSubnetIDs:
    Description: Private SubnetIDs where the Network LoadBalancer will be placed (Select min 2, max 3)
    Type: "List<AWS::EC2::Subnet::Id>"

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - c3.large
    - c3.xlarge
    - c4.large
    ConstraintDescription: must be a valid EC2 instance type.

  HttpPort:
    Type: String
    Default: 80
    Description: HTTP port

  AllowedClientCIDR:
    Description: The client network CIDR allowed to access the service. The allowed block size is between a /32 netmask and /8 netmask
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: ^[.0-9]*\/([89]|[12][0-9]|3[0-2])$

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    Description: Default latest Amazon Linux2 AMI.

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: HTTP parameter
      Parameters:
      - HttpPort
      - InstanceType
      - LatestAmiId
      - KeyName

    - Label:
        default: Network parameter
      Parameters:
      - VpcId
      - PrivateSubnetIDs
      - AllowedClientCIDR

    ParameterLabels:
      HttpPort:
        default: HTTP Port
      InstanceType:
        default: Instance Type
      LatestAmiId:
        default: AMI ID
      KeyName:
        default: SSH Key name
      VpcId:
        default: VPC ID
      PrivateSubnetIDs:
        default: Private Subnet IDs
      AllowedClientCIDR:
        default: Allowed client CIDR


Conditions:

  AddSSHKey: !Not
   - !Equals
     - ''
     - !Ref KeyName


Resources:

  B2BEgressRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "B2BEgressRole-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  B2BEgressNLBInternalWeb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      Type: network
      Name: B2BEgressNLBInternalWeb
      Subnets: !Ref PrivateSubnetIDs

  B2BEgressNLBInternalTGWeb:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: B2BEgressNLBInternalTGWeb
      Port: !Ref HttpPort
      Protocol: TCP
      VpcId: !Ref VpcId
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60

  B2BEgressNLBInternalListWeb:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref B2BEgressNLBInternalTGWeb
      LoadBalancerArn: !Ref B2BEgressNLBInternalWeb
      Port: !Ref HttpPort
      Protocol: TCP

  B2BEgressInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      InstanceProfileName: !Sub "B2BEgressInstanceProfile-${AWS::StackName}"
      Roles:
        - !Ref B2BEgressRole

  B2BEgressNLBInternalWebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to B2B Egress Proxy
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - CidrIp: !Ref AllowedClientCIDR
        FromPort: !Ref HttpPort
        ToPort: !Ref HttpPort
        IpProtocol: tcp

  B2BEgressASGInternalWeb:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Ref PrivateSubnetIDs
      Cooldown: 120
      LaunchConfigurationName: !Ref B2BEgressASGInternalWebLaunchConfig
      MaxSize: 3
      MinSize: 1
      TargetGroupARNs:
        - Ref: B2BEgressNLBInternalTGWeb
      TerminationPolicies:
      - OldestInstance
      Tags:
      - Key: Name
        PropagateAtLaunch: 'true'
        Value: B2BEgressASGInternalWeb
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
        Count: '1'
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 1
        PauseTime: PT15M
        WaitOnResourceSignals: 'true'
        SuspendProcesses:
        - ScheduledActions

  B2BEgressASGInternalWebLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      Comment: Configures B2B Egress Instance
      AWS::CloudFormation::Init:
        config:
          files:
            "/etc/cfn/cfn-hup.conf":
              content: !Sub |
                [main]
                stack= ${AWS::StackId}
                region=${AWS::Region}
                interval=5
              mode: "000400"
              owner: "root"
              group: "root"
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.B2BEgressASGInternalWebLaunchConfig.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource B2BEgressASGInternalWebLaunchConfig --region ${AWS::Region}
                runas=root
              mode: "000400"
              owner: "root"
              group: "root"
    Properties:
      ImageId:  !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !If
         - AddSSHKey
         - !Ref KeyName
         - !Ref "AWS::NoValue"
      SecurityGroups:
      - !Ref B2BEgressNLBInternalWebSG

      IamInstanceProfile:
        Ref: B2BEgressInstanceProfile
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash -xe

            export http_proxy=http://B2BEgressNLBProxy-a77ca70ec553d510.elb.ap-southeast-2.amazonaws.com:3128 && export https_proxy=$http_proxy
            export no_proxy=169.254.169.254

            # Install AWS CLI
            yum install -y awscli

            # Install AWS CloudFormation bootstrap scripts
            yum install -y aws-cfn-bootstrap

            # Start cfn-init
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r B2BEgressASGInternalWebLaunchConfig --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
            # Start up the cfn-hup daemon to listen for changes to the launch configuration metadata
            /opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'

            # install nginx from amazon-linux-extras
            amazon-linux-extras install -y nginx1

            # Start nginx
            systemctl start nginx

            # All done so signal success
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource B2BEgressASGInternalWeb --region ${AWS::Region}
            echo "Userdata execution completed"

Outputs:

  B2BEgressNLBInternalWebFQDN:
    Description: NLB FQDN to be used by clients
    Value: !GetAtt B2BEgressNLBInternalWeb.DNSName
    Export:
        Name: B2BEgressNLBInternalWebFQDN

  InternalWebPort:
    Description: HTTP Port
    Value: !Ref HttpPort
    Export:
      Name: InternalWebPort

  InternalWebSettings:
    Description: HTTP URL
    Value: !Sub "http://${B2BEgressNLBInternalWeb.DNSName}:${HttpPort}"
    Export:
      Name: InternalWebSettings
